// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: game_content_video_config.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Muziverse.Proto.GameContent.Api.VideoConfig {
  public static partial class GameVideoLinkConfigService
  {
    static readonly string __ServiceName = "gamecontent.videoconfig.GameVideoLinkConfigService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Muziverse.Proto.GameContent.Api.VideoConfig.GetVideoLinkConfigRequest> __Marshaller_gamecontent_videoconfig_GetVideoLinkConfigRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Muziverse.Proto.GameContent.Api.VideoConfig.GetVideoLinkConfigRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Muziverse.Proto.GameContent.Api.VideoConfig.VideoLinkConfigResponse> __Marshaller_gamecontent_videoconfig_VideoLinkConfigResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Muziverse.Proto.GameContent.Api.VideoConfig.VideoLinkConfigResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Muziverse.Proto.GameContent.Api.VideoConfig.GetVideoLinkConfigByIdsRequest> __Marshaller_gamecontent_videoconfig_GetVideoLinkConfigByIdsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Muziverse.Proto.GameContent.Api.VideoConfig.GetVideoLinkConfigByIdsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Muziverse.Proto.GameContent.Api.VideoConfig.CreateVideoLinkConfigRequest> __Marshaller_gamecontent_videoconfig_CreateVideoLinkConfigRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Muziverse.Proto.GameContent.Api.VideoConfig.CreateVideoLinkConfigRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Protobuf.WellKnownTypes.Empty.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Muziverse.Proto.GameContent.Api.VideoConfig.UpdateVideoLinkConfigRequest> __Marshaller_gamecontent_videoconfig_UpdateVideoLinkConfigRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Muziverse.Proto.GameContent.Api.VideoConfig.UpdateVideoLinkConfigRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Muziverse.Proto.GameContent.Api.VideoConfig.DeleteVideoLinkConfigRequest> __Marshaller_gamecontent_videoconfig_DeleteVideoLinkConfigRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Muziverse.Proto.GameContent.Api.VideoConfig.DeleteVideoLinkConfigRequest.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Muziverse.Proto.GameContent.Api.VideoConfig.GetVideoLinkConfigRequest, global::Muziverse.Proto.GameContent.Api.VideoConfig.VideoLinkConfigResponse> __Method_GetVideoLinkConfig = new grpc::Method<global::Muziverse.Proto.GameContent.Api.VideoConfig.GetVideoLinkConfigRequest, global::Muziverse.Proto.GameContent.Api.VideoConfig.VideoLinkConfigResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetVideoLinkConfig",
        __Marshaller_gamecontent_videoconfig_GetVideoLinkConfigRequest,
        __Marshaller_gamecontent_videoconfig_VideoLinkConfigResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Muziverse.Proto.GameContent.Api.VideoConfig.GetVideoLinkConfigByIdsRequest, global::Muziverse.Proto.GameContent.Api.VideoConfig.VideoLinkConfigResponse> __Method_GetVideoLinkConfigByIds = new grpc::Method<global::Muziverse.Proto.GameContent.Api.VideoConfig.GetVideoLinkConfigByIdsRequest, global::Muziverse.Proto.GameContent.Api.VideoConfig.VideoLinkConfigResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetVideoLinkConfigByIds",
        __Marshaller_gamecontent_videoconfig_GetVideoLinkConfigByIdsRequest,
        __Marshaller_gamecontent_videoconfig_VideoLinkConfigResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Muziverse.Proto.GameContent.Api.VideoConfig.CreateVideoLinkConfigRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_CreateVideoLinkConfig = new grpc::Method<global::Muziverse.Proto.GameContent.Api.VideoConfig.CreateVideoLinkConfigRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateVideoLinkConfig",
        __Marshaller_gamecontent_videoconfig_CreateVideoLinkConfigRequest,
        __Marshaller_google_protobuf_Empty);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Muziverse.Proto.GameContent.Api.VideoConfig.UpdateVideoLinkConfigRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_UpdateVideoLinkConfig = new grpc::Method<global::Muziverse.Proto.GameContent.Api.VideoConfig.UpdateVideoLinkConfigRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateVideoLinkConfig",
        __Marshaller_gamecontent_videoconfig_UpdateVideoLinkConfigRequest,
        __Marshaller_google_protobuf_Empty);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Muziverse.Proto.GameContent.Api.VideoConfig.DeleteVideoLinkConfigRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_DeleteVideoLinkConfig = new grpc::Method<global::Muziverse.Proto.GameContent.Api.VideoConfig.DeleteVideoLinkConfigRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteVideoLinkConfig",
        __Marshaller_gamecontent_videoconfig_DeleteVideoLinkConfigRequest,
        __Marshaller_google_protobuf_Empty);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Muziverse.Proto.GameContent.Api.VideoConfig.GameContentVideoConfigReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of GameVideoLinkConfigService</summary>
    [grpc::BindServiceMethod(typeof(GameVideoLinkConfigService), "BindService")]
    public abstract partial class GameVideoLinkConfigServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Muziverse.Proto.GameContent.Api.VideoConfig.VideoLinkConfigResponse> GetVideoLinkConfig(global::Muziverse.Proto.GameContent.Api.VideoConfig.GetVideoLinkConfigRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Muziverse.Proto.GameContent.Api.VideoConfig.VideoLinkConfigResponse> GetVideoLinkConfigByIds(global::Muziverse.Proto.GameContent.Api.VideoConfig.GetVideoLinkConfigByIdsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> CreateVideoLinkConfig(global::Muziverse.Proto.GameContent.Api.VideoConfig.CreateVideoLinkConfigRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> UpdateVideoLinkConfig(global::Muziverse.Proto.GameContent.Api.VideoConfig.UpdateVideoLinkConfigRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> DeleteVideoLinkConfig(global::Muziverse.Proto.GameContent.Api.VideoConfig.DeleteVideoLinkConfigRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for GameVideoLinkConfigService</summary>
    public partial class GameVideoLinkConfigServiceClient : grpc::ClientBase<GameVideoLinkConfigServiceClient>
    {
      /// <summary>Creates a new client for GameVideoLinkConfigService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public GameVideoLinkConfigServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for GameVideoLinkConfigService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public GameVideoLinkConfigServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected GameVideoLinkConfigServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected GameVideoLinkConfigServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Muziverse.Proto.GameContent.Api.VideoConfig.VideoLinkConfigResponse GetVideoLinkConfig(global::Muziverse.Proto.GameContent.Api.VideoConfig.GetVideoLinkConfigRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetVideoLinkConfig(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Muziverse.Proto.GameContent.Api.VideoConfig.VideoLinkConfigResponse GetVideoLinkConfig(global::Muziverse.Proto.GameContent.Api.VideoConfig.GetVideoLinkConfigRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetVideoLinkConfig, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Muziverse.Proto.GameContent.Api.VideoConfig.VideoLinkConfigResponse> GetVideoLinkConfigAsync(global::Muziverse.Proto.GameContent.Api.VideoConfig.GetVideoLinkConfigRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetVideoLinkConfigAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Muziverse.Proto.GameContent.Api.VideoConfig.VideoLinkConfigResponse> GetVideoLinkConfigAsync(global::Muziverse.Proto.GameContent.Api.VideoConfig.GetVideoLinkConfigRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetVideoLinkConfig, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Muziverse.Proto.GameContent.Api.VideoConfig.VideoLinkConfigResponse GetVideoLinkConfigByIds(global::Muziverse.Proto.GameContent.Api.VideoConfig.GetVideoLinkConfigByIdsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetVideoLinkConfigByIds(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Muziverse.Proto.GameContent.Api.VideoConfig.VideoLinkConfigResponse GetVideoLinkConfigByIds(global::Muziverse.Proto.GameContent.Api.VideoConfig.GetVideoLinkConfigByIdsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetVideoLinkConfigByIds, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Muziverse.Proto.GameContent.Api.VideoConfig.VideoLinkConfigResponse> GetVideoLinkConfigByIdsAsync(global::Muziverse.Proto.GameContent.Api.VideoConfig.GetVideoLinkConfigByIdsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetVideoLinkConfigByIdsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Muziverse.Proto.GameContent.Api.VideoConfig.VideoLinkConfigResponse> GetVideoLinkConfigByIdsAsync(global::Muziverse.Proto.GameContent.Api.VideoConfig.GetVideoLinkConfigByIdsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetVideoLinkConfigByIds, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty CreateVideoLinkConfig(global::Muziverse.Proto.GameContent.Api.VideoConfig.CreateVideoLinkConfigRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateVideoLinkConfig(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty CreateVideoLinkConfig(global::Muziverse.Proto.GameContent.Api.VideoConfig.CreateVideoLinkConfigRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateVideoLinkConfig, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> CreateVideoLinkConfigAsync(global::Muziverse.Proto.GameContent.Api.VideoConfig.CreateVideoLinkConfigRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateVideoLinkConfigAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> CreateVideoLinkConfigAsync(global::Muziverse.Proto.GameContent.Api.VideoConfig.CreateVideoLinkConfigRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateVideoLinkConfig, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty UpdateVideoLinkConfig(global::Muziverse.Proto.GameContent.Api.VideoConfig.UpdateVideoLinkConfigRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateVideoLinkConfig(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty UpdateVideoLinkConfig(global::Muziverse.Proto.GameContent.Api.VideoConfig.UpdateVideoLinkConfigRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateVideoLinkConfig, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> UpdateVideoLinkConfigAsync(global::Muziverse.Proto.GameContent.Api.VideoConfig.UpdateVideoLinkConfigRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateVideoLinkConfigAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> UpdateVideoLinkConfigAsync(global::Muziverse.Proto.GameContent.Api.VideoConfig.UpdateVideoLinkConfigRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateVideoLinkConfig, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DeleteVideoLinkConfig(global::Muziverse.Proto.GameContent.Api.VideoConfig.DeleteVideoLinkConfigRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteVideoLinkConfig(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DeleteVideoLinkConfig(global::Muziverse.Proto.GameContent.Api.VideoConfig.DeleteVideoLinkConfigRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteVideoLinkConfig, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DeleteVideoLinkConfigAsync(global::Muziverse.Proto.GameContent.Api.VideoConfig.DeleteVideoLinkConfigRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteVideoLinkConfigAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DeleteVideoLinkConfigAsync(global::Muziverse.Proto.GameContent.Api.VideoConfig.DeleteVideoLinkConfigRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteVideoLinkConfig, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override GameVideoLinkConfigServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new GameVideoLinkConfigServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(GameVideoLinkConfigServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetVideoLinkConfig, serviceImpl.GetVideoLinkConfig)
          .AddMethod(__Method_GetVideoLinkConfigByIds, serviceImpl.GetVideoLinkConfigByIds)
          .AddMethod(__Method_CreateVideoLinkConfig, serviceImpl.CreateVideoLinkConfig)
          .AddMethod(__Method_UpdateVideoLinkConfig, serviceImpl.UpdateVideoLinkConfig)
          .AddMethod(__Method_DeleteVideoLinkConfig, serviceImpl.DeleteVideoLinkConfig).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, GameVideoLinkConfigServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetVideoLinkConfig, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Muziverse.Proto.GameContent.Api.VideoConfig.GetVideoLinkConfigRequest, global::Muziverse.Proto.GameContent.Api.VideoConfig.VideoLinkConfigResponse>(serviceImpl.GetVideoLinkConfig));
      serviceBinder.AddMethod(__Method_GetVideoLinkConfigByIds, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Muziverse.Proto.GameContent.Api.VideoConfig.GetVideoLinkConfigByIdsRequest, global::Muziverse.Proto.GameContent.Api.VideoConfig.VideoLinkConfigResponse>(serviceImpl.GetVideoLinkConfigByIds));
      serviceBinder.AddMethod(__Method_CreateVideoLinkConfig, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Muziverse.Proto.GameContent.Api.VideoConfig.CreateVideoLinkConfigRequest, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.CreateVideoLinkConfig));
      serviceBinder.AddMethod(__Method_UpdateVideoLinkConfig, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Muziverse.Proto.GameContent.Api.VideoConfig.UpdateVideoLinkConfigRequest, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.UpdateVideoLinkConfig));
      serviceBinder.AddMethod(__Method_DeleteVideoLinkConfig, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Muziverse.Proto.GameContent.Api.VideoConfig.DeleteVideoLinkConfigRequest, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.DeleteVideoLinkConfig));
    }

  }
}
#endregion
