// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: paymentint_wallet.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Paymentint.Wallet {
  public static partial class PaymentIntWalletService
  {
    static readonly string __ServiceName = "paymentint.wallet.PaymentIntWalletService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Paymentint.Wallet.ImportWalletRequest> __Marshaller_paymentint_wallet_ImportWalletRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Paymentint.Wallet.ImportWalletRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Paymentint.Wallet.ListImportWalletResponse> __Marshaller_paymentint_wallet_ListImportWalletResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Paymentint.Wallet.ListImportWalletResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Paymentint.Wallet.AllocateWalletRequest> __Marshaller_paymentint_wallet_AllocateWalletRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Paymentint.Wallet.AllocateWalletRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Paymentint.Wallet.ListAllocateWalletResponse> __Marshaller_paymentint_wallet_ListAllocateWalletResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Paymentint.Wallet.ListAllocateWalletResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Paymentint.Wallet.ImportWalletRequest, global::Paymentint.Wallet.ListImportWalletResponse> __Method_ImportWallet = new grpc::Method<global::Paymentint.Wallet.ImportWalletRequest, global::Paymentint.Wallet.ListImportWalletResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ImportWallet",
        __Marshaller_paymentint_wallet_ImportWalletRequest,
        __Marshaller_paymentint_wallet_ListImportWalletResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Paymentint.Wallet.AllocateWalletRequest, global::Paymentint.Wallet.ListAllocateWalletResponse> __Method_AllocateWallet = new grpc::Method<global::Paymentint.Wallet.AllocateWalletRequest, global::Paymentint.Wallet.ListAllocateWalletResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AllocateWallet",
        __Marshaller_paymentint_wallet_AllocateWalletRequest,
        __Marshaller_paymentint_wallet_ListAllocateWalletResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Paymentint.Wallet.PaymentintWalletReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of PaymentIntWalletService</summary>
    [grpc::BindServiceMethod(typeof(PaymentIntWalletService), "BindService")]
    public abstract partial class PaymentIntWalletServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Paymentint.Wallet.ListImportWalletResponse> ImportWallet(global::Paymentint.Wallet.ImportWalletRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Paymentint.Wallet.ListAllocateWalletResponse> AllocateWallet(global::Paymentint.Wallet.AllocateWalletRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for PaymentIntWalletService</summary>
    public partial class PaymentIntWalletServiceClient : grpc::ClientBase<PaymentIntWalletServiceClient>
    {
      /// <summary>Creates a new client for PaymentIntWalletService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public PaymentIntWalletServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for PaymentIntWalletService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public PaymentIntWalletServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected PaymentIntWalletServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected PaymentIntWalletServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Paymentint.Wallet.ListImportWalletResponse ImportWallet(global::Paymentint.Wallet.ImportWalletRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ImportWallet(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Paymentint.Wallet.ListImportWalletResponse ImportWallet(global::Paymentint.Wallet.ImportWalletRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ImportWallet, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Paymentint.Wallet.ListImportWalletResponse> ImportWalletAsync(global::Paymentint.Wallet.ImportWalletRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ImportWalletAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Paymentint.Wallet.ListImportWalletResponse> ImportWalletAsync(global::Paymentint.Wallet.ImportWalletRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ImportWallet, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Paymentint.Wallet.ListAllocateWalletResponse AllocateWallet(global::Paymentint.Wallet.AllocateWalletRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AllocateWallet(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Paymentint.Wallet.ListAllocateWalletResponse AllocateWallet(global::Paymentint.Wallet.AllocateWalletRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AllocateWallet, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Paymentint.Wallet.ListAllocateWalletResponse> AllocateWalletAsync(global::Paymentint.Wallet.AllocateWalletRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AllocateWalletAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Paymentint.Wallet.ListAllocateWalletResponse> AllocateWalletAsync(global::Paymentint.Wallet.AllocateWalletRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AllocateWallet, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override PaymentIntWalletServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new PaymentIntWalletServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(PaymentIntWalletServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_ImportWallet, serviceImpl.ImportWallet)
          .AddMethod(__Method_AllocateWallet, serviceImpl.AllocateWallet).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, PaymentIntWalletServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_ImportWallet, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Paymentint.Wallet.ImportWalletRequest, global::Paymentint.Wallet.ListImportWalletResponse>(serviceImpl.ImportWallet));
      serviceBinder.AddMethod(__Method_AllocateWallet, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Paymentint.Wallet.AllocateWalletRequest, global::Paymentint.Wallet.ListAllocateWalletResponse>(serviceImpl.AllocateWallet));
    }

  }
}
#endregion
