// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: domain/user_wallet_info.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from domain/user_wallet_info.proto</summary>
public static partial class UserWalletInfoReflection {

  #region Descriptor
  /// <summary>File descriptor for domain/user_wallet_info.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static UserWalletInfoReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Ch1kb21haW4vdXNlcl93YWxsZXRfaW5mby5wcm90bxofZG9tYWluL3VzZXJf",
          "d2FsbGV0X2NvbW1vbi5wcm90bxofZ29vZ2xlL3Byb3RvYnVmL3RpbWVzdGFt",
          "cC5wcm90byLTAQoOV2FsbGV0UmVzcG9uc2USCgoCaWQYASABKAMSDwoHYWRk",
          "cmVzcxgCIAEoCRIdCgZzdGF0dXMYAyABKA4yDS5XYWxsZXRTdGF0dXMSJQoK",
          "Y3VycmVuY2llcxgEIAMoCzIRLkN1cnJlbmN5UmVzcG9uc2USLgoKY3JlYXRl",
          "ZF9hdBgFIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKdXBk",
          "YXRlZF9hdBgGIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAiIQoP",
          "Q3VycmVuY3lSZXF1ZXN0Eg4KBnN5bWJvbBgCIAEoCSLrAQoQQ3VycmVuY3lS",
          "ZXNwb25zZRIKCgJpZBgBIAEoAxIOCgZzeW1ib2wYAiABKAkSFQoNdG90YWxf",
          "YmFsYW5jZRgDIAEoCRIZChFhdmFpbGFibGVfYmFsYW5jZRgEIAEoCRITCgtj",
          "YW5fZGVwb3NpdBgFIAEoCBIUCgxjYW5fd2l0aGRyYXcYBiABKAgSLgoKY3Jl",
          "YXRlZF9hdBgHIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoK",
          "dXBkYXRlZF9hdBgIIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBC",
          "igEKImlvLm11eml2ZXJzZS5wcm90by51c2VyLmFwaS53YWxsZXRCE1VzZXJX",
          "YWxsZXRJbmZvUHJvdG9QAVpNZ2l0bGFiLmNvbS9tdXppdmVyc2UvY29tbW9u",
          "L3Byb3RvZ29nZW5lcmF0b3IvdXNlci13YWxsZXQtcHJvdG8tYXBpL3BrZy9k",
          "b21haW5iBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::UserWalletCommonReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::WalletResponse), global::WalletResponse.Parser, new[]{ "Id", "Address", "Status", "Currencies", "CreatedAt", "UpdatedAt" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::CurrencyRequest), global::CurrencyRequest.Parser, new[]{ "Symbol" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::CurrencyResponse), global::CurrencyResponse.Parser, new[]{ "Id", "Symbol", "TotalBalance", "AvailableBalance", "CanDeposit", "CanWithdraw", "CreatedAt", "UpdatedAt" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class WalletResponse : pb::IMessage<WalletResponse>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<WalletResponse> _parser = new pb::MessageParser<WalletResponse>(() => new WalletResponse());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<WalletResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::UserWalletInfoReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public WalletResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public WalletResponse(WalletResponse other) : this() {
    id_ = other.id_;
    address_ = other.address_;
    status_ = other.status_;
    currencies_ = other.currencies_.Clone();
    createdAt_ = other.createdAt_ != null ? other.createdAt_.Clone() : null;
    updatedAt_ = other.updatedAt_ != null ? other.updatedAt_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public WalletResponse Clone() {
    return new WalletResponse(this);
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 1;
  private long id_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Id {
    get { return id_; }
    set {
      id_ = value;
    }
  }

  /// <summary>Field number for the "address" field.</summary>
  public const int AddressFieldNumber = 2;
  private string address_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Address {
    get { return address_; }
    set {
      address_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "status" field.</summary>
  public const int StatusFieldNumber = 3;
  private global::WalletStatus status_ = global::WalletStatus.Available;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::WalletStatus Status {
    get { return status_; }
    set {
      status_ = value;
    }
  }

  /// <summary>Field number for the "currencies" field.</summary>
  public const int CurrenciesFieldNumber = 4;
  private static readonly pb::FieldCodec<global::CurrencyResponse> _repeated_currencies_codec
      = pb::FieldCodec.ForMessage(34, global::CurrencyResponse.Parser);
  private readonly pbc::RepeatedField<global::CurrencyResponse> currencies_ = new pbc::RepeatedField<global::CurrencyResponse>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::CurrencyResponse> Currencies {
    get { return currencies_; }
  }

  /// <summary>Field number for the "created_at" field.</summary>
  public const int CreatedAtFieldNumber = 5;
  private global::Google.Protobuf.WellKnownTypes.Timestamp createdAt_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Google.Protobuf.WellKnownTypes.Timestamp CreatedAt {
    get { return createdAt_; }
    set {
      createdAt_ = value;
    }
  }

  /// <summary>Field number for the "updated_at" field.</summary>
  public const int UpdatedAtFieldNumber = 6;
  private global::Google.Protobuf.WellKnownTypes.Timestamp updatedAt_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Google.Protobuf.WellKnownTypes.Timestamp UpdatedAt {
    get { return updatedAt_; }
    set {
      updatedAt_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as WalletResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(WalletResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if (Address != other.Address) return false;
    if (Status != other.Status) return false;
    if(!currencies_.Equals(other.currencies_)) return false;
    if (!object.Equals(CreatedAt, other.CreatedAt)) return false;
    if (!object.Equals(UpdatedAt, other.UpdatedAt)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Id != 0L) hash ^= Id.GetHashCode();
    if (Address.Length != 0) hash ^= Address.GetHashCode();
    if (Status != global::WalletStatus.Available) hash ^= Status.GetHashCode();
    hash ^= currencies_.GetHashCode();
    if (createdAt_ != null) hash ^= CreatedAt.GetHashCode();
    if (updatedAt_ != null) hash ^= UpdatedAt.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Id != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Id);
    }
    if (Address.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Address);
    }
    if (Status != global::WalletStatus.Available) {
      output.WriteRawTag(24);
      output.WriteEnum((int) Status);
    }
    currencies_.WriteTo(output, _repeated_currencies_codec);
    if (createdAt_ != null) {
      output.WriteRawTag(42);
      output.WriteMessage(CreatedAt);
    }
    if (updatedAt_ != null) {
      output.WriteRawTag(50);
      output.WriteMessage(UpdatedAt);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Id != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Id);
    }
    if (Address.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Address);
    }
    if (Status != global::WalletStatus.Available) {
      output.WriteRawTag(24);
      output.WriteEnum((int) Status);
    }
    currencies_.WriteTo(ref output, _repeated_currencies_codec);
    if (createdAt_ != null) {
      output.WriteRawTag(42);
      output.WriteMessage(CreatedAt);
    }
    if (updatedAt_ != null) {
      output.WriteRawTag(50);
      output.WriteMessage(UpdatedAt);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Id != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
    }
    if (Address.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Address);
    }
    if (Status != global::WalletStatus.Available) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
    }
    size += currencies_.CalculateSize(_repeated_currencies_codec);
    if (createdAt_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(CreatedAt);
    }
    if (updatedAt_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(UpdatedAt);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(WalletResponse other) {
    if (other == null) {
      return;
    }
    if (other.Id != 0L) {
      Id = other.Id;
    }
    if (other.Address.Length != 0) {
      Address = other.Address;
    }
    if (other.Status != global::WalletStatus.Available) {
      Status = other.Status;
    }
    currencies_.Add(other.currencies_);
    if (other.createdAt_ != null) {
      if (createdAt_ == null) {
        CreatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
      }
      CreatedAt.MergeFrom(other.CreatedAt);
    }
    if (other.updatedAt_ != null) {
      if (updatedAt_ == null) {
        UpdatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
      }
      UpdatedAt.MergeFrom(other.UpdatedAt);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Id = input.ReadInt64();
          break;
        }
        case 18: {
          Address = input.ReadString();
          break;
        }
        case 24: {
          Status = (global::WalletStatus) input.ReadEnum();
          break;
        }
        case 34: {
          currencies_.AddEntriesFrom(input, _repeated_currencies_codec);
          break;
        }
        case 42: {
          if (createdAt_ == null) {
            CreatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
          }
          input.ReadMessage(CreatedAt);
          break;
        }
        case 50: {
          if (updatedAt_ == null) {
            UpdatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
          }
          input.ReadMessage(UpdatedAt);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Id = input.ReadInt64();
          break;
        }
        case 18: {
          Address = input.ReadString();
          break;
        }
        case 24: {
          Status = (global::WalletStatus) input.ReadEnum();
          break;
        }
        case 34: {
          currencies_.AddEntriesFrom(ref input, _repeated_currencies_codec);
          break;
        }
        case 42: {
          if (createdAt_ == null) {
            CreatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
          }
          input.ReadMessage(CreatedAt);
          break;
        }
        case 50: {
          if (updatedAt_ == null) {
            UpdatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
          }
          input.ReadMessage(UpdatedAt);
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class CurrencyRequest : pb::IMessage<CurrencyRequest>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<CurrencyRequest> _parser = new pb::MessageParser<CurrencyRequest>(() => new CurrencyRequest());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<CurrencyRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::UserWalletInfoReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CurrencyRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CurrencyRequest(CurrencyRequest other) : this() {
    symbol_ = other.symbol_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CurrencyRequest Clone() {
    return new CurrencyRequest(this);
  }

  /// <summary>Field number for the "symbol" field.</summary>
  public const int SymbolFieldNumber = 2;
  private string symbol_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Symbol {
    get { return symbol_; }
    set {
      symbol_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as CurrencyRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(CurrencyRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Symbol != other.Symbol) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Symbol.Length != 0) hash ^= Symbol.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Symbol.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Symbol);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Symbol.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Symbol);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Symbol.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Symbol);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(CurrencyRequest other) {
    if (other == null) {
      return;
    }
    if (other.Symbol.Length != 0) {
      Symbol = other.Symbol;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 18: {
          Symbol = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 18: {
          Symbol = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class CurrencyResponse : pb::IMessage<CurrencyResponse>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<CurrencyResponse> _parser = new pb::MessageParser<CurrencyResponse>(() => new CurrencyResponse());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<CurrencyResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::UserWalletInfoReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CurrencyResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CurrencyResponse(CurrencyResponse other) : this() {
    id_ = other.id_;
    symbol_ = other.symbol_;
    totalBalance_ = other.totalBalance_;
    availableBalance_ = other.availableBalance_;
    canDeposit_ = other.canDeposit_;
    canWithdraw_ = other.canWithdraw_;
    createdAt_ = other.createdAt_ != null ? other.createdAt_.Clone() : null;
    updatedAt_ = other.updatedAt_ != null ? other.updatedAt_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CurrencyResponse Clone() {
    return new CurrencyResponse(this);
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 1;
  private long id_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Id {
    get { return id_; }
    set {
      id_ = value;
    }
  }

  /// <summary>Field number for the "symbol" field.</summary>
  public const int SymbolFieldNumber = 2;
  private string symbol_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Symbol {
    get { return symbol_; }
    set {
      symbol_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "total_balance" field.</summary>
  public const int TotalBalanceFieldNumber = 3;
  private string totalBalance_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string TotalBalance {
    get { return totalBalance_; }
    set {
      totalBalance_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "available_balance" field.</summary>
  public const int AvailableBalanceFieldNumber = 4;
  private string availableBalance_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string AvailableBalance {
    get { return availableBalance_; }
    set {
      availableBalance_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "can_deposit" field.</summary>
  public const int CanDepositFieldNumber = 5;
  private bool canDeposit_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool CanDeposit {
    get { return canDeposit_; }
    set {
      canDeposit_ = value;
    }
  }

  /// <summary>Field number for the "can_withdraw" field.</summary>
  public const int CanWithdrawFieldNumber = 6;
  private bool canWithdraw_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool CanWithdraw {
    get { return canWithdraw_; }
    set {
      canWithdraw_ = value;
    }
  }

  /// <summary>Field number for the "created_at" field.</summary>
  public const int CreatedAtFieldNumber = 7;
  private global::Google.Protobuf.WellKnownTypes.Timestamp createdAt_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Google.Protobuf.WellKnownTypes.Timestamp CreatedAt {
    get { return createdAt_; }
    set {
      createdAt_ = value;
    }
  }

  /// <summary>Field number for the "updated_at" field.</summary>
  public const int UpdatedAtFieldNumber = 8;
  private global::Google.Protobuf.WellKnownTypes.Timestamp updatedAt_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Google.Protobuf.WellKnownTypes.Timestamp UpdatedAt {
    get { return updatedAt_; }
    set {
      updatedAt_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as CurrencyResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(CurrencyResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if (Symbol != other.Symbol) return false;
    if (TotalBalance != other.TotalBalance) return false;
    if (AvailableBalance != other.AvailableBalance) return false;
    if (CanDeposit != other.CanDeposit) return false;
    if (CanWithdraw != other.CanWithdraw) return false;
    if (!object.Equals(CreatedAt, other.CreatedAt)) return false;
    if (!object.Equals(UpdatedAt, other.UpdatedAt)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Id != 0L) hash ^= Id.GetHashCode();
    if (Symbol.Length != 0) hash ^= Symbol.GetHashCode();
    if (TotalBalance.Length != 0) hash ^= TotalBalance.GetHashCode();
    if (AvailableBalance.Length != 0) hash ^= AvailableBalance.GetHashCode();
    if (CanDeposit != false) hash ^= CanDeposit.GetHashCode();
    if (CanWithdraw != false) hash ^= CanWithdraw.GetHashCode();
    if (createdAt_ != null) hash ^= CreatedAt.GetHashCode();
    if (updatedAt_ != null) hash ^= UpdatedAt.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Id != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Id);
    }
    if (Symbol.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Symbol);
    }
    if (TotalBalance.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(TotalBalance);
    }
    if (AvailableBalance.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(AvailableBalance);
    }
    if (CanDeposit != false) {
      output.WriteRawTag(40);
      output.WriteBool(CanDeposit);
    }
    if (CanWithdraw != false) {
      output.WriteRawTag(48);
      output.WriteBool(CanWithdraw);
    }
    if (createdAt_ != null) {
      output.WriteRawTag(58);
      output.WriteMessage(CreatedAt);
    }
    if (updatedAt_ != null) {
      output.WriteRawTag(66);
      output.WriteMessage(UpdatedAt);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Id != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Id);
    }
    if (Symbol.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Symbol);
    }
    if (TotalBalance.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(TotalBalance);
    }
    if (AvailableBalance.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(AvailableBalance);
    }
    if (CanDeposit != false) {
      output.WriteRawTag(40);
      output.WriteBool(CanDeposit);
    }
    if (CanWithdraw != false) {
      output.WriteRawTag(48);
      output.WriteBool(CanWithdraw);
    }
    if (createdAt_ != null) {
      output.WriteRawTag(58);
      output.WriteMessage(CreatedAt);
    }
    if (updatedAt_ != null) {
      output.WriteRawTag(66);
      output.WriteMessage(UpdatedAt);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Id != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
    }
    if (Symbol.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Symbol);
    }
    if (TotalBalance.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(TotalBalance);
    }
    if (AvailableBalance.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(AvailableBalance);
    }
    if (CanDeposit != false) {
      size += 1 + 1;
    }
    if (CanWithdraw != false) {
      size += 1 + 1;
    }
    if (createdAt_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(CreatedAt);
    }
    if (updatedAt_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(UpdatedAt);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(CurrencyResponse other) {
    if (other == null) {
      return;
    }
    if (other.Id != 0L) {
      Id = other.Id;
    }
    if (other.Symbol.Length != 0) {
      Symbol = other.Symbol;
    }
    if (other.TotalBalance.Length != 0) {
      TotalBalance = other.TotalBalance;
    }
    if (other.AvailableBalance.Length != 0) {
      AvailableBalance = other.AvailableBalance;
    }
    if (other.CanDeposit != false) {
      CanDeposit = other.CanDeposit;
    }
    if (other.CanWithdraw != false) {
      CanWithdraw = other.CanWithdraw;
    }
    if (other.createdAt_ != null) {
      if (createdAt_ == null) {
        CreatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
      }
      CreatedAt.MergeFrom(other.CreatedAt);
    }
    if (other.updatedAt_ != null) {
      if (updatedAt_ == null) {
        UpdatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
      }
      UpdatedAt.MergeFrom(other.UpdatedAt);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Id = input.ReadInt64();
          break;
        }
        case 18: {
          Symbol = input.ReadString();
          break;
        }
        case 26: {
          TotalBalance = input.ReadString();
          break;
        }
        case 34: {
          AvailableBalance = input.ReadString();
          break;
        }
        case 40: {
          CanDeposit = input.ReadBool();
          break;
        }
        case 48: {
          CanWithdraw = input.ReadBool();
          break;
        }
        case 58: {
          if (createdAt_ == null) {
            CreatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
          }
          input.ReadMessage(CreatedAt);
          break;
        }
        case 66: {
          if (updatedAt_ == null) {
            UpdatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
          }
          input.ReadMessage(UpdatedAt);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Id = input.ReadInt64();
          break;
        }
        case 18: {
          Symbol = input.ReadString();
          break;
        }
        case 26: {
          TotalBalance = input.ReadString();
          break;
        }
        case 34: {
          AvailableBalance = input.ReadString();
          break;
        }
        case 40: {
          CanDeposit = input.ReadBool();
          break;
        }
        case 48: {
          CanWithdraw = input.ReadBool();
          break;
        }
        case 58: {
          if (createdAt_ == null) {
            CreatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
          }
          input.ReadMessage(CreatedAt);
          break;
        }
        case 66: {
          if (updatedAt_ == null) {
            UpdatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
          }
          input.ReadMessage(UpdatedAt);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
