// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: domain/user_flow_status.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Muziverse.Proto.User.Domain {

  /// <summary>Holder for reflection information generated from domain/user_flow_status.proto</summary>
  public static partial class UserFlowStatusReflection {

    #region Descriptor
    /// <summary>File descriptor for domain/user_flow_status.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UserFlowStatusReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch1kb21haW4vdXNlcl9mbG93X3N0YXR1cy5wcm90bypaCg5Vc2VyRmxvd1N0",
            "YXR1cxISCg5VRl9VTlNQRUNJRklFRBAAEhYKEldBSVRJTkdfQUNUSVZBVElP",
            "ThABEg0KCUNPTVBMRVRFRBACEg0KCUNIQUxMRU5HRRADQp0BCh5pby5tdXpp",
            "dmVyc2UucHJvdG8udXNlci5kb21haW5CE1VzZXJGbG93U3RhdHVzUHJvdG9Q",
            "AVpGZ2l0bGFiLmNvbS9tdXppdmVyc2UvY29tbW9uL3Byb3RvZ29nZW5lcmF0",
            "b3IvdXNlci1wcm90by1hcGkvcGtnL2RvbWFpbqoCG011eml2ZXJzZS5Qcm90",
            "by5Vc2VyLkRvbWFpbmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Muziverse.Proto.User.Domain.UserFlowStatus), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum UserFlowStatus {
    [pbr::OriginalName("UF_UNSPECIFIED")] UfUnspecified = 0,
    [pbr::OriginalName("WAITING_ACTIVATION")] WaitingActivation = 1,
    [pbr::OriginalName("COMPLETED")] Completed = 2,
    [pbr::OriginalName("CHALLENGE")] Challenge = 3,
  }

  #endregion

}

#endregion Designer generated code
