// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: user_token.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Muziverse.Proto.User.Api.Token {

  /// <summary>Holder for reflection information generated from user_token.proto</summary>
  public static partial class UserTokenReflection {

    #region Descriptor
    /// <summary>File descriptor for user_token.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UserTokenReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChB1c2VyX3Rva2VuLnByb3RvEg5pZGVudGl0eS50b2tlbhoYZG9tYWluL3Vz",
            "ZXJfY29tbW9uLnByb3RvGhtnb29nbGUvcHJvdG9idWYvZW1wdHkucHJvdG8y",
            "UQoQVXNlclRva2VuU2VydmljZRI9CgxSZWZyZXNoVG9rZW4SFi5nb29nbGUu",
            "cHJvdG9idWYuRW1wdHkaEy5BY2Nlc3NGbG93UmVzcG9uc2UiAEKhAQohaW8u",
            "bXV6aXZlcnNlLnByb3RvLnVzZXIuYXBpLnRva2VuQg5Vc2VyVG9rZW5Qcm90",
            "b1ABWklnaXRsYWIuY29tL211eml2ZXJzZS9jb21tb24vcHJvdG9nb2dlbmVy",
            "YXRvci91c2VyLXByb3RvLWFwaS9wa2cvYXBpL3Rva2VuqgIeTXV6aXZlcnNl",
            "LlByb3RvLlVzZXIuQXBpLlRva2VuYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Muziverse.Proto.User.Domain.UserCommonReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
