// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: user_change_identity.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Muziverse.Proto.User.Api.User.ChangeIdentity {

  /// <summary>Holder for reflection information generated from user_change_identity.proto</summary>
  public static partial class UserChangeIdentityReflection {

    #region Descriptor
    /// <summary>File descriptor for user_change_identity.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UserChangeIdentityReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chp1c2VyX2NoYW5nZV9pZGVudGl0eS5wcm90bxIVaWRlbnRpdHkubW9kaWZp",
            "Y2F0aW9uGhd2YWxpZGF0ZS92YWxpZGF0ZS5wcm90bxobZ29vZ2xlL3Byb3Rv",
            "YnVmL2VtcHR5LnByb3RvInMKElJlcXVlc3RPdHBJZGVudGl0eRI9Cgdjb250",
            "ZXh0GAEgASgOMiwuaWRlbnRpdHkubW9kaWZpY2F0aW9uLkNoYW5nZUlkZW50",
            "aXR5Q29udGV4dBIeCgVlbWFpbBgCIAEoCUIP+kIMcgoQBRj+AWAB0AEBIsQF",
            "ChVDaGFuZ2VJZGVudGl0eVJlcXVlc3QSPQoHY29udGV4dBgBIAEoDjIsLmlk",
            "ZW50aXR5Lm1vZGlmaWNhdGlvbi5DaGFuZ2VJZGVudGl0eUNvbnRleHQSXQoP",
            "Y2hhbmdlX3Bhc3N3b3JkGAIgASgLMkIuaWRlbnRpdHkubW9kaWZpY2F0aW9u",
            "LkNoYW5nZUlkZW50aXR5UmVxdWVzdC5DaGFuZ2VQYXNzd29yZFJlcXVlc3RI",
            "ABJdCg9jcmVhdGVfcGFzc3dvcmQYAyABKAsyQi5pZGVudGl0eS5tb2RpZmlj",
            "YXRpb24uQ2hhbmdlSWRlbnRpdHlSZXF1ZXN0LkNyZWF0ZVBhc3N3b3JkUmVx",
            "dWVzdEgAEm8KGWNyZWF0ZV9lbWFpbF9hbmRfcGFzc3dvcmQYBCABKAsySi5p",
            "ZGVudGl0eS5tb2RpZmljYXRpb24uQ2hhbmdlSWRlbnRpdHlSZXF1ZXN0LkNy",
            "ZWF0ZUVtYWlsQW5kUGFzc3dvcmRSZXF1ZXN0SAAaewoVQ2hhbmdlUGFzc3dv",
            "cmRSZXF1ZXN0EiIKDG9sZF9wYXNzd29yZBgBIAEoCUIM+kIJcgcQCBhA0AEB",
            "EiIKDG5ld19wYXNzd29yZBgCIAEoCUIM+kIJcgcQCBhA0AEBEhoKCG90cF9j",
            "b2RlGAMgASgJQgj6QgVyA9ABARpbCh1DcmVhdGVFbWFpbEFuZFBhc3N3b3Jk",
            "UmVxdWVzdBIeCghwYXNzd29yZBgCIAEoCUIM+kIJcgcQCBhA0AEBEhoKCG90",
            "cF9jb2RlGAMgASgJQgj6QgVyA9ABARpTChVDcmVhdGVQYXNzd29yZFJlcXVl",
            "c3QSHgoIcGFzc3dvcmQYAiABKAlCDPpCCXIHEAgYQNABARIaCghvdHBfY29k",
            "ZRgDIAEoCUII+kIFcgPQAQFCDgoHbWVzc2FnZRID+EIBKrABChVDaGFuZ2VJ",
            "ZGVudGl0eUNvbnRleHQSJwojQ0hBTkdFX0lERU5USVRZX0NPTlRFWFRfVU5T",
            "UEVDSUZJRUQQABIRCg1BQ1RJVkFURV9VU0VSEAESEgoOUkVTRVRfUEFTU1dP",
            "UkQQAhITCg9DSEFOR0VfUEFTU1dPUkQQAxITCg9DUkVBVEVfUEFTU1dPUkQQ",
            "BBIdChlDUkVBVEVfRU1BSUxfQU5EX1BBU1NXT1JEEAUymgIKGVVzZXJDaGFu",
            "Z2VJZGVudGl0eVNlcnZpY2USUQoKUmVxdWVzdE90cBIpLmlkZW50aXR5Lm1v",
            "ZGlmaWNhdGlvbi5SZXF1ZXN0T3RwSWRlbnRpdHkaFi5nb29nbGUucHJvdG9i",
            "dWYuRW1wdHkiABJQCglSZXNlbmRPdHASKS5pZGVudGl0eS5tb2RpZmljYXRp",
            "b24uUmVxdWVzdE90cElkZW50aXR5GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5",
            "IgASWAoOQ2hhbmdlSWRlbnRpdHkSLC5pZGVudGl0eS5tb2RpZmljYXRpb24u",
            "Q2hhbmdlSWRlbnRpdHlSZXF1ZXN0GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5",
            "IgBC2gEKMWlvLm11eml2ZXJzZS5wcm90by51c2VyLmFwaS5pZGVudGl0eS5t",
            "b2RpZmljYXRpb25CF1VzZXJDaGFuZ2VJZGVudGl0eVByb3RvUAFaW2dpdGxh",
            "Yi5jb20vbXV6aXZlcnNlL2NvbW1vbi9wcm90b2dvZ2VuZXJhdG9yL3VzZXIt",
            "cHJvdG8tYXBpL3BrZy9hcGkvaWRlbnRpdHkvQ2hhbmdlSWRlbnRpdHmqAixN",
            "dXppdmVyc2UuUHJvdG8uVXNlci5BcGkuVXNlci5DaGFuZ2VJZGVudGl0eWIG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Validate.ValidateReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityContext), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Muziverse.Proto.User.Api.User.ChangeIdentity.RequestOtpIdentity), global::Muziverse.Proto.User.Api.User.ChangeIdentity.RequestOtpIdentity.Parser, new[]{ "Context", "Email" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityRequest), global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityRequest.Parser, new[]{ "Context", "ChangePassword", "CreatePassword", "CreateEmailAndPassword" }, new[]{ "Message" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityRequest.Types.ChangePasswordRequest), global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityRequest.Types.ChangePasswordRequest.Parser, new[]{ "OldPassword", "NewPassword", "OtpCode" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityRequest.Types.CreateEmailAndPasswordRequest), global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityRequest.Types.CreateEmailAndPasswordRequest.Parser, new[]{ "Password", "OtpCode" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityRequest.Types.CreatePasswordRequest), global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityRequest.Types.CreatePasswordRequest.Parser, new[]{ "Password", "OtpCode" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Enums
  public enum ChangeIdentityContext {
    [pbr::OriginalName("CHANGE_IDENTITY_CONTEXT_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("ACTIVATE_USER")] ActivateUser = 1,
    [pbr::OriginalName("RESET_PASSWORD")] ResetPassword = 2,
    [pbr::OriginalName("CHANGE_PASSWORD")] ChangePassword = 3,
    [pbr::OriginalName("CREATE_PASSWORD")] CreatePassword = 4,
    [pbr::OriginalName("CREATE_EMAIL_AND_PASSWORD")] CreateEmailAndPassword = 5,
  }

  #endregion

  #region Messages
  public sealed partial class RequestOtpIdentity : pb::IMessage<RequestOtpIdentity>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RequestOtpIdentity> _parser = new pb::MessageParser<RequestOtpIdentity>(() => new RequestOtpIdentity());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RequestOtpIdentity> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Muziverse.Proto.User.Api.User.ChangeIdentity.UserChangeIdentityReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RequestOtpIdentity() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RequestOtpIdentity(RequestOtpIdentity other) : this() {
      context_ = other.context_;
      email_ = other.email_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RequestOtpIdentity Clone() {
      return new RequestOtpIdentity(this);
    }

    /// <summary>Field number for the "context" field.</summary>
    public const int ContextFieldNumber = 1;
    private global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityContext context_ = global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityContext.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityContext Context {
      get { return context_; }
      set {
        context_ = value;
      }
    }

    /// <summary>Field number for the "email" field.</summary>
    public const int EmailFieldNumber = 2;
    private string email_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Email {
      get { return email_; }
      set {
        email_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RequestOtpIdentity);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RequestOtpIdentity other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Context != other.Context) return false;
      if (Email != other.Email) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Context != global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityContext.Unspecified) hash ^= Context.GetHashCode();
      if (Email.Length != 0) hash ^= Email.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Context != global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityContext.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Context);
      }
      if (Email.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Email);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Context != global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityContext.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Context);
      }
      if (Email.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Email);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Context != global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityContext.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Context);
      }
      if (Email.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Email);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RequestOtpIdentity other) {
      if (other == null) {
        return;
      }
      if (other.Context != global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityContext.Unspecified) {
        Context = other.Context;
      }
      if (other.Email.Length != 0) {
        Email = other.Email;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Context = (global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityContext) input.ReadEnum();
            break;
          }
          case 18: {
            Email = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Context = (global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityContext) input.ReadEnum();
            break;
          }
          case 18: {
            Email = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ChangeIdentityRequest : pb::IMessage<ChangeIdentityRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ChangeIdentityRequest> _parser = new pb::MessageParser<ChangeIdentityRequest>(() => new ChangeIdentityRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ChangeIdentityRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Muziverse.Proto.User.Api.User.ChangeIdentity.UserChangeIdentityReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChangeIdentityRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChangeIdentityRequest(ChangeIdentityRequest other) : this() {
      context_ = other.context_;
      switch (other.MessageCase) {
        case MessageOneofCase.ChangePassword:
          ChangePassword = other.ChangePassword.Clone();
          break;
        case MessageOneofCase.CreatePassword:
          CreatePassword = other.CreatePassword.Clone();
          break;
        case MessageOneofCase.CreateEmailAndPassword:
          CreateEmailAndPassword = other.CreateEmailAndPassword.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChangeIdentityRequest Clone() {
      return new ChangeIdentityRequest(this);
    }

    /// <summary>Field number for the "context" field.</summary>
    public const int ContextFieldNumber = 1;
    private global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityContext context_ = global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityContext.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityContext Context {
      get { return context_; }
      set {
        context_ = value;
      }
    }

    /// <summary>Field number for the "change_password" field.</summary>
    public const int ChangePasswordFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityRequest.Types.ChangePasswordRequest ChangePassword {
      get { return messageCase_ == MessageOneofCase.ChangePassword ? (global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityRequest.Types.ChangePasswordRequest) message_ : null; }
      set {
        message_ = value;
        messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.ChangePassword;
      }
    }

    /// <summary>Field number for the "create_password" field.</summary>
    public const int CreatePasswordFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityRequest.Types.CreatePasswordRequest CreatePassword {
      get { return messageCase_ == MessageOneofCase.CreatePassword ? (global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityRequest.Types.CreatePasswordRequest) message_ : null; }
      set {
        message_ = value;
        messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.CreatePassword;
      }
    }

    /// <summary>Field number for the "create_email_and_password" field.</summary>
    public const int CreateEmailAndPasswordFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityRequest.Types.CreateEmailAndPasswordRequest CreateEmailAndPassword {
      get { return messageCase_ == MessageOneofCase.CreateEmailAndPassword ? (global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityRequest.Types.CreateEmailAndPasswordRequest) message_ : null; }
      set {
        message_ = value;
        messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.CreateEmailAndPassword;
      }
    }

    private object message_;
    /// <summary>Enum of possible cases for the "message" oneof.</summary>
    public enum MessageOneofCase {
      None = 0,
      ChangePassword = 2,
      CreatePassword = 3,
      CreateEmailAndPassword = 4,
    }
    private MessageOneofCase messageCase_ = MessageOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MessageOneofCase MessageCase {
      get { return messageCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMessage() {
      messageCase_ = MessageOneofCase.None;
      message_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ChangeIdentityRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ChangeIdentityRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Context != other.Context) return false;
      if (!object.Equals(ChangePassword, other.ChangePassword)) return false;
      if (!object.Equals(CreatePassword, other.CreatePassword)) return false;
      if (!object.Equals(CreateEmailAndPassword, other.CreateEmailAndPassword)) return false;
      if (MessageCase != other.MessageCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Context != global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityContext.Unspecified) hash ^= Context.GetHashCode();
      if (messageCase_ == MessageOneofCase.ChangePassword) hash ^= ChangePassword.GetHashCode();
      if (messageCase_ == MessageOneofCase.CreatePassword) hash ^= CreatePassword.GetHashCode();
      if (messageCase_ == MessageOneofCase.CreateEmailAndPassword) hash ^= CreateEmailAndPassword.GetHashCode();
      hash ^= (int) messageCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Context != global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityContext.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Context);
      }
      if (messageCase_ == MessageOneofCase.ChangePassword) {
        output.WriteRawTag(18);
        output.WriteMessage(ChangePassword);
      }
      if (messageCase_ == MessageOneofCase.CreatePassword) {
        output.WriteRawTag(26);
        output.WriteMessage(CreatePassword);
      }
      if (messageCase_ == MessageOneofCase.CreateEmailAndPassword) {
        output.WriteRawTag(34);
        output.WriteMessage(CreateEmailAndPassword);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Context != global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityContext.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Context);
      }
      if (messageCase_ == MessageOneofCase.ChangePassword) {
        output.WriteRawTag(18);
        output.WriteMessage(ChangePassword);
      }
      if (messageCase_ == MessageOneofCase.CreatePassword) {
        output.WriteRawTag(26);
        output.WriteMessage(CreatePassword);
      }
      if (messageCase_ == MessageOneofCase.CreateEmailAndPassword) {
        output.WriteRawTag(34);
        output.WriteMessage(CreateEmailAndPassword);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Context != global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityContext.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Context);
      }
      if (messageCase_ == MessageOneofCase.ChangePassword) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChangePassword);
      }
      if (messageCase_ == MessageOneofCase.CreatePassword) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CreatePassword);
      }
      if (messageCase_ == MessageOneofCase.CreateEmailAndPassword) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CreateEmailAndPassword);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ChangeIdentityRequest other) {
      if (other == null) {
        return;
      }
      if (other.Context != global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityContext.Unspecified) {
        Context = other.Context;
      }
      switch (other.MessageCase) {
        case MessageOneofCase.ChangePassword:
          if (ChangePassword == null) {
            ChangePassword = new global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityRequest.Types.ChangePasswordRequest();
          }
          ChangePassword.MergeFrom(other.ChangePassword);
          break;
        case MessageOneofCase.CreatePassword:
          if (CreatePassword == null) {
            CreatePassword = new global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityRequest.Types.CreatePasswordRequest();
          }
          CreatePassword.MergeFrom(other.CreatePassword);
          break;
        case MessageOneofCase.CreateEmailAndPassword:
          if (CreateEmailAndPassword == null) {
            CreateEmailAndPassword = new global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityRequest.Types.CreateEmailAndPasswordRequest();
          }
          CreateEmailAndPassword.MergeFrom(other.CreateEmailAndPassword);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Context = (global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityContext) input.ReadEnum();
            break;
          }
          case 18: {
            global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityRequest.Types.ChangePasswordRequest subBuilder = new global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityRequest.Types.ChangePasswordRequest();
            if (messageCase_ == MessageOneofCase.ChangePassword) {
              subBuilder.MergeFrom(ChangePassword);
            }
            input.ReadMessage(subBuilder);
            ChangePassword = subBuilder;
            break;
          }
          case 26: {
            global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityRequest.Types.CreatePasswordRequest subBuilder = new global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityRequest.Types.CreatePasswordRequest();
            if (messageCase_ == MessageOneofCase.CreatePassword) {
              subBuilder.MergeFrom(CreatePassword);
            }
            input.ReadMessage(subBuilder);
            CreatePassword = subBuilder;
            break;
          }
          case 34: {
            global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityRequest.Types.CreateEmailAndPasswordRequest subBuilder = new global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityRequest.Types.CreateEmailAndPasswordRequest();
            if (messageCase_ == MessageOneofCase.CreateEmailAndPassword) {
              subBuilder.MergeFrom(CreateEmailAndPassword);
            }
            input.ReadMessage(subBuilder);
            CreateEmailAndPassword = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Context = (global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityContext) input.ReadEnum();
            break;
          }
          case 18: {
            global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityRequest.Types.ChangePasswordRequest subBuilder = new global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityRequest.Types.ChangePasswordRequest();
            if (messageCase_ == MessageOneofCase.ChangePassword) {
              subBuilder.MergeFrom(ChangePassword);
            }
            input.ReadMessage(subBuilder);
            ChangePassword = subBuilder;
            break;
          }
          case 26: {
            global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityRequest.Types.CreatePasswordRequest subBuilder = new global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityRequest.Types.CreatePasswordRequest();
            if (messageCase_ == MessageOneofCase.CreatePassword) {
              subBuilder.MergeFrom(CreatePassword);
            }
            input.ReadMessage(subBuilder);
            CreatePassword = subBuilder;
            break;
          }
          case 34: {
            global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityRequest.Types.CreateEmailAndPasswordRequest subBuilder = new global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityRequest.Types.CreateEmailAndPasswordRequest();
            if (messageCase_ == MessageOneofCase.CreateEmailAndPassword) {
              subBuilder.MergeFrom(CreateEmailAndPassword);
            }
            input.ReadMessage(subBuilder);
            CreateEmailAndPassword = subBuilder;
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the ChangeIdentityRequest message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public sealed partial class ChangePasswordRequest : pb::IMessage<ChangePasswordRequest>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<ChangePasswordRequest> _parser = new pb::MessageParser<ChangePasswordRequest>(() => new ChangePasswordRequest());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<ChangePasswordRequest> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityRequest.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ChangePasswordRequest() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ChangePasswordRequest(ChangePasswordRequest other) : this() {
          oldPassword_ = other.oldPassword_;
          newPassword_ = other.newPassword_;
          otpCode_ = other.otpCode_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ChangePasswordRequest Clone() {
          return new ChangePasswordRequest(this);
        }

        /// <summary>Field number for the "old_password" field.</summary>
        public const int OldPasswordFieldNumber = 1;
        private string oldPassword_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string OldPassword {
          get { return oldPassword_; }
          set {
            oldPassword_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "new_password" field.</summary>
        public const int NewPasswordFieldNumber = 2;
        private string newPassword_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string NewPassword {
          get { return newPassword_; }
          set {
            newPassword_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "otp_code" field.</summary>
        public const int OtpCodeFieldNumber = 3;
        private string otpCode_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string OtpCode {
          get { return otpCode_; }
          set {
            otpCode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as ChangePasswordRequest);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(ChangePasswordRequest other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (OldPassword != other.OldPassword) return false;
          if (NewPassword != other.NewPassword) return false;
          if (OtpCode != other.OtpCode) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (OldPassword.Length != 0) hash ^= OldPassword.GetHashCode();
          if (NewPassword.Length != 0) hash ^= NewPassword.GetHashCode();
          if (OtpCode.Length != 0) hash ^= OtpCode.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (OldPassword.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(OldPassword);
          }
          if (NewPassword.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(NewPassword);
          }
          if (OtpCode.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(OtpCode);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (OldPassword.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(OldPassword);
          }
          if (NewPassword.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(NewPassword);
          }
          if (OtpCode.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(OtpCode);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (OldPassword.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(OldPassword);
          }
          if (NewPassword.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(NewPassword);
          }
          if (OtpCode.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(OtpCode);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(ChangePasswordRequest other) {
          if (other == null) {
            return;
          }
          if (other.OldPassword.Length != 0) {
            OldPassword = other.OldPassword;
          }
          if (other.NewPassword.Length != 0) {
            NewPassword = other.NewPassword;
          }
          if (other.OtpCode.Length != 0) {
            OtpCode = other.OtpCode;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                OldPassword = input.ReadString();
                break;
              }
              case 18: {
                NewPassword = input.ReadString();
                break;
              }
              case 26: {
                OtpCode = input.ReadString();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                OldPassword = input.ReadString();
                break;
              }
              case 18: {
                NewPassword = input.ReadString();
                break;
              }
              case 26: {
                OtpCode = input.ReadString();
                break;
              }
            }
          }
        }
        #endif

      }

      public sealed partial class CreateEmailAndPasswordRequest : pb::IMessage<CreateEmailAndPasswordRequest>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<CreateEmailAndPasswordRequest> _parser = new pb::MessageParser<CreateEmailAndPasswordRequest>(() => new CreateEmailAndPasswordRequest());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<CreateEmailAndPasswordRequest> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityRequest.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public CreateEmailAndPasswordRequest() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public CreateEmailAndPasswordRequest(CreateEmailAndPasswordRequest other) : this() {
          password_ = other.password_;
          otpCode_ = other.otpCode_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public CreateEmailAndPasswordRequest Clone() {
          return new CreateEmailAndPasswordRequest(this);
        }

        /// <summary>Field number for the "password" field.</summary>
        public const int PasswordFieldNumber = 2;
        private string password_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Password {
          get { return password_; }
          set {
            password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "otp_code" field.</summary>
        public const int OtpCodeFieldNumber = 3;
        private string otpCode_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string OtpCode {
          get { return otpCode_; }
          set {
            otpCode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as CreateEmailAndPasswordRequest);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(CreateEmailAndPasswordRequest other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Password != other.Password) return false;
          if (OtpCode != other.OtpCode) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (Password.Length != 0) hash ^= Password.GetHashCode();
          if (OtpCode.Length != 0) hash ^= OtpCode.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (Password.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(Password);
          }
          if (OtpCode.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(OtpCode);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (Password.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(Password);
          }
          if (OtpCode.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(OtpCode);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (Password.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
          }
          if (OtpCode.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(OtpCode);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(CreateEmailAndPasswordRequest other) {
          if (other == null) {
            return;
          }
          if (other.Password.Length != 0) {
            Password = other.Password;
          }
          if (other.OtpCode.Length != 0) {
            OtpCode = other.OtpCode;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 18: {
                Password = input.ReadString();
                break;
              }
              case 26: {
                OtpCode = input.ReadString();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 18: {
                Password = input.ReadString();
                break;
              }
              case 26: {
                OtpCode = input.ReadString();
                break;
              }
            }
          }
        }
        #endif

      }

      public sealed partial class CreatePasswordRequest : pb::IMessage<CreatePasswordRequest>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<CreatePasswordRequest> _parser = new pb::MessageParser<CreatePasswordRequest>(() => new CreatePasswordRequest());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<CreatePasswordRequest> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Muziverse.Proto.User.Api.User.ChangeIdentity.ChangeIdentityRequest.Descriptor.NestedTypes[2]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public CreatePasswordRequest() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public CreatePasswordRequest(CreatePasswordRequest other) : this() {
          password_ = other.password_;
          otpCode_ = other.otpCode_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public CreatePasswordRequest Clone() {
          return new CreatePasswordRequest(this);
        }

        /// <summary>Field number for the "password" field.</summary>
        public const int PasswordFieldNumber = 2;
        private string password_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Password {
          get { return password_; }
          set {
            password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "otp_code" field.</summary>
        public const int OtpCodeFieldNumber = 3;
        private string otpCode_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string OtpCode {
          get { return otpCode_; }
          set {
            otpCode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as CreatePasswordRequest);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(CreatePasswordRequest other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Password != other.Password) return false;
          if (OtpCode != other.OtpCode) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (Password.Length != 0) hash ^= Password.GetHashCode();
          if (OtpCode.Length != 0) hash ^= OtpCode.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (Password.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(Password);
          }
          if (OtpCode.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(OtpCode);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (Password.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(Password);
          }
          if (OtpCode.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(OtpCode);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (Password.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
          }
          if (OtpCode.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(OtpCode);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(CreatePasswordRequest other) {
          if (other == null) {
            return;
          }
          if (other.Password.Length != 0) {
            Password = other.Password;
          }
          if (other.OtpCode.Length != 0) {
            OtpCode = other.OtpCode;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 18: {
                Password = input.ReadString();
                break;
              }
              case 26: {
                OtpCode = input.ReadString();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 18: {
                Password = input.ReadString();
                break;
              }
              case 26: {
                OtpCode = input.ReadString();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
