// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: domain/resource_state.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from domain/resource_state.proto</summary>
public static partial class ResourceStateReflection {

  #region Descriptor
  /// <summary>File descriptor for domain/resource_state.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ResourceStateReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Chtkb21haW4vcmVzb3VyY2Vfc3RhdGUucHJvdG8qXgoNUmVzb3VyY2VTdGF0",
          "ZRIeChpSRVNPVVJDRV9TVEFURV9VTlNQRUNJRklFRBAAEg0KCUFWQUlMQUJM",
          "RRABEhAKDFVOX0FWQUlMQUJMRRACEgwKCE9CU09MRVRFEANChgEKImlvLm11",
          "eml2ZXJzZS5wcm90by5yZXNvdXJjZS5kb21haW5CElJlc291cmNlU3RhdGVQ",
          "cm90b1ABWkpnaXRsYWIuY29tL211eml2ZXJzZS9jb21tb24vcHJvdG9nb2dl",
          "bmVyYXRvci9yZXNvdXJjZS1wcm90by1hcGkvcGtnL2RvbWFpbmIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ResourceState), }, null, null));
  }
  #endregion

}
#region Enums
public enum ResourceState {
  [pbr::OriginalName("RESOURCE_STATE_UNSPECIFIED")] Unspecified = 0,
  [pbr::OriginalName("AVAILABLE")] Available = 1,
  [pbr::OriginalName("UN_AVAILABLE")] UnAvailable = 2,
  [pbr::OriginalName("OBSOLETE")] Obsolete = 3,
}

#endregion


#endregion Designer generated code
